name: Deploy WASI Bot

on:
  push:
    branches:
      - main  encher ce workflow lors d'un push sur la branche "main"
      
jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3

    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  

    
    - name: Install dependencies
      run: npm install

    
    - name: Setup environment variables
      run: |
        echo "BOT_NAME=${{ secrets.BOT_NAME }}" >> .env
        echo "OWNER_NUMBER=${{ secrets.OWNER_NUMBER }}" >> .env
        echo "PREFIX=${{ secrets.PREFIX }}" >> .env
        echo "SESSION_PATH=./session/session.json" >> .env

    
    - name: Check for session file
      run: |
        mkdir -p session
        if [ ! -f "./session/session.json" ]; then
          echo '{}' > ./session/session.json
        fi

    
    - name: Start Bot
      run: node index.js
